query GetProductBySlug ($slug: String) {
    products(filters: { slug: { eq: $slug }, publishedAt: { notNull: true }}) {
        data {
            id
            attributes {
                slug
                title
                price
                salePrice
                product_keys (filters: { publishedAt: { notNull: true }}) {
                    data {
                        __typename
                    }
                }
                product_type {
                    data {
                        attributes {
                            title
                        }
                    }
                }
                delivery_method {
                    data {
                        attributes {
                            title
                        }
                    }
                }
                views
                description
                instruction
                platforms {
                    data {
                        attributes {
                            title
                        }
                    }
                }
                images {
                    data {
                        attributes {
                            url
                        }
                    }
                }
            }
        }
    }
}
